# Copyright 2026 Nav2PlannerBattle contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Geometry / artifact-consistency tests for the closed-loop course generator.

These check that each course's world, occupancy map, and goals are mutually
consistent and that the courses are non-trivial — without ROS or Gazebo (the
closed-loop run needs a real ROS host; see docs/simulation.md section 10.5). The
committed worlds/ and maps/ artifacts are regenerated by ``gen_courses.main()``.
"""

import importlib.util
import os
import xml.dom.minidom

ROBOT_MARGIN = 0.22  # TB3 waffle footprint radius (approx)

_HERE = os.path.dirname(__file__)
_MOD = os.path.join(_HERE, '..', 'nav2_diffusion_sim', 'gen_courses.py')
_spec = importlib.util.spec_from_file_location('gen_courses', _MOD)
gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gen)


def _straight_blocked(name, p0, p1, margin=0.0, n=300):
    return any(
        gen.point_in_any_wall(
            name, p0[0] + (p1[0] - p0[0]) * t / n,
            p0[1] + (p1[1] - p0[1]) * t / n, margin)
        for t in range(n + 1))


def test_start_and_goals_are_clear():
    for name, spec in gen.COURSE_SPECS.items():
        sx, sy, _ = spec['start']
        assert not gen.point_in_any_wall(name, sx, sy, ROBOT_MARGIN), \
            "course '{}' start is inside a wall".format(name)
        for label, gx, gy, _yaw, _t in spec['goals']:
            assert not gen.point_in_any_wall(name, gx, gy, ROBOT_MARGIN), \
                "course '{}' goal '{}' is inside a wall".format(name, label)


def test_obstacle_courses_block_the_straight_line():
    # gap / slalom / micro-mouse mazes must force a detour; centred must not.
    for name in ('gap', 'slalom', 'micro_mouse_easy', 'micro_mouse_hard'):
        spec = gen.COURSE_SPECS[name]
        st, g = spec['start'], spec['goals'][0]
        assert _straight_blocked(name, (st[0], st[1]), (g[1], g[2])), \
            "course '{}' should block the straight line".format(name)
    cspec = gen.COURSE_SPECS['centred']
    st, g = cspec['start'], cspec['goals'][0]
    assert not _straight_blocked('centred', (st[0], st[1]), (g[1], g[2])), \
        'centred gap should be threadable straight ahead'


def test_each_course_goal_is_reachable_through_a_clear_gap():
    # A simple monotone-x corridor exists: for every wall x-column the robot
    # crosses, there is a y within reach that clears it. We assert the goal's
    # final approach column and the start column are clear (sanity), plus that
    # the straight segment from start to goal, allowed to deviate in y, is not
    # fully walled (there is at least one fully-free vertical line near a gap).
    for name, spec in gen.COURSE_SPECS.items():
        xmin, xmax, ymin, ymax = spec['extent']
        # There must be at least one free cell column-spanning path point in the
        # interior (the gap). Scan a fine grid for any free interior point off
        # the start line, proving a gap exists with clearance.
        found_gap = False
        y = ymin + 0.5
        while y <= ymax - 0.5 and not found_gap:
            x = (xmin + xmax) / 2.0  # the wall column(s) sit around x=0..1
            if not gen.point_in_any_wall(name, x, y, ROBOT_MARGIN):
                found_gap = True
            y += 0.1
        assert found_gap, "course '{}' has no clear gap column".format(name)


def test_occupancy_map_has_free_and_occupied_and_matches_extent():
    for name, spec in gen.COURSE_SPECS.items():
        pgm, yaml, (w, h) = gen.occupancy_map(name, resolution=0.05)
        xmin, xmax, ymin, ymax = spec['extent']
        assert w == round((xmax - xmin) / 0.05)
        assert h == round((ymax - ymin) / 0.05)
        # P5 header then w*h bytes of pixel data.
        header = 'P5\n{} {}\n255\n'.format(w, h).encode('ascii')
        assert pgm.startswith(header)
        body = pgm[len(header):]
        assert len(body) == w * h
        assert 0 in body, 'no occupied (wall) cells'
        assert 254 in body, 'no free cells'
        assert 'origin: [{}, {}, 0.0]'.format(xmin, ymin) in yaml
        assert '{}.pgm'.format(name) in yaml


def test_world_sdf_is_well_formed_and_has_all_wall_models():
    for name in gen.COURSE_SPECS:
        sdf = gen.world_sdf(name)
        # Namespaced xacro tags parse fine in a non-validating DOM parser.
        xml.dom.minidom.parseString(sdf)
        assert sdf.count('<model name="wall_') == len(gen.all_walls(name))
        assert '<model name="ground_plane">' in sdf
        assert 'gz-sim-sensors-system' in sdf  # LiDAR will render


def test_course_missions_are_parseable_specs():
    for name in gen.COURSE_SPECS:
        for spec in gen.course_missions(name):
            parts = spec.split('|')
            assert len(parts) == 5
            for field in parts[1:]:
                float(field)


def test_committed_artifacts_match_the_specs():
    # The worlds/ and maps/ checked into the package must equal a fresh render,
    # so a spec edit without re-running gen_courses.main() fails CI.
    pkg = os.path.join(_HERE, '..')
    for name in gen.COURSE_SPECS:
        world_path = os.path.join(pkg, 'worlds', name + '.sdf.xacro')
        with open(world_path) as fh:
            assert fh.read() == gen.world_sdf(name), \
                'worlds/{}.sdf.xacro is stale; re-run gen_courses.main()'.format(name)
        pgm, yaml, _ = gen.occupancy_map(name)
        with open(os.path.join(pkg, 'maps', name + '.yaml')) as fh:
            assert fh.read() == yaml, \
                'maps/{}.yaml is stale; re-run gen_courses.main()'.format(name)
        with open(os.path.join(pkg, 'maps', name + '.pgm'), 'rb') as fh:
            assert fh.read() == pgm, \
                'maps/{}.pgm is stale; re-run gen_courses.main()'.format(name)
